apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push : false
  artifacts:
    - image: sergeykhaustovich/auth
      context: auth
      docker:
        buildArgs:
          NPM_TOKEN: "{{.NPM_TOKEN}}"
        dockerfile:
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: sergeykhaustovich/client
      context: client
      docker:
        dockerfile:
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: sergeykhaustovich/tickets
      context: tickets
      docker:
        buildArgs:
          NPM_TOKEN: "{{.NPM_TOKEN}}"
        dockerfile:
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: sergeykhaustovich/orders
      context: orders
      docker:
        buildArgs:
          NPM_TOKEN: "{{.NPM_TOKEN}}"
        dockerfile:
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: sergeykhaustovich/expiration
      context: expiration
      docker:
        buildArgs:
          NPM_TOKEN: "{{.NPM_TOKEN}}"
        dockerfile:
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: sergeykhaustovich/payments
      context: payments
      docker:
        buildArgs:
          NPM_TOKEN: "{{.NPM_TOKEN}}"
        dockerfile:
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
